# NumPy Creating Arrays

In [32]:
import numpy as np

### Create Array

#### List

In [15]:
# list []
arr = np.array([1,2,3,4,5])

In [16]:
print(arr)

[1 2 3 4 5]


In [22]:
print(type(arr))

<class 'numpy.ndarray'>


#### tuple

In [23]:
# tuple
arr = np.array((1,2,3,4,5))

In [19]:
print(arr)

[1 2 3 4 5]


In [20]:
print(type(arr))

<class 'numpy.ndarray'>


### Dimension in Arrays

#### 0-D Arrays

In [24]:
arr = np.array(42)
print(arr)

42


#### 1-D Arrays

In [25]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


#### 2-D Arrays

In [27]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


#### 3-D Arrays

In [31]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Check Number of Dimension

In [36]:
a = np.array(42)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,4,5]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher Dimensional Arrays

In [37]:
arr = np.array([1,2,3,4], ndmin= 5)
print(arr)
print("number of dimensions : ",arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions :  5
