# NumPy Array Indexing

### Access Array Elements

In [3]:
import numpy as np

#### Access 1-D Arrays

In [6]:
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[1])
print(arr[2]+arr[3])

1
2
7


#### Access 2-D Arrays

In [17]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])
print(arr[1,4])

2
10


#### Access 3-D Arrays

In [18]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


### Negative Indexing

In [19]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


In [15]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr[1][0])

50
