# NumPy Array Slicing

### Slicing arrays

In [21]:
import numpy as np

In [22]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


### Negative Slicing

In [23]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


### STEP

In [24]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])
print(arr[::2])

[2 4]
[1 3 5 7]


### Slicing 2-D Arrays

In [25]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2,2])

[7 8 9]
[3 8]
