# The Difference Between Copy and View

In [1]:
import numpy as np

### COPY

In [4]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


### VIEW

In [5]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


### Make Changes in the VIEW

In [6]:
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 25
print(arr)
print(x)

[25  2  3  4  5]
[25  2  3  4  5]


### Check if Array Owns its Data

In [7]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
