# NumPy Array Reshaping

In [2]:
import numpy as np

### Reshape From 1-D to 2-D

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Reshape From 1-D to 3-D

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.copy()
newarr = newarr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Can We Reshape Into any Shape

In [13]:
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(3,3)
print(newarr)
# NO

ValueError: cannot reshape array of size 8 into shape (3,3)

### Returns Copy or View 

In [14]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)
#return view

[1 2 3 4 5 6 7 8]


### Unknown Dimension

In [17]:
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flattening the arrays

In [18]:
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]
